### PR TITLE
Fix PHP missing var warning.

### PR DESCRIPTION
**Pull request by tareiking**
$taxonomy->slug does not exist in this context, however $taxonomy->query_var does, lets use that instead.

### CODE REVIEW

**Comment by felixarntz** [comment]
Thanks @tareiking! Let's use `$taxonomy_slug` instead which is defined at this point and produces the result that `$taxonomy->slug` originally would have.

**Comment by tareiking** [comment]
Good suggestion, updated PR.

**Comment by felixarntz** [comment]
I think in line 124 you confused the two variable names, the first one ("name" attribute) should remain `$taxonomy->query_var` while the ID must be `$taxonomy_slug`.

**Comment by tareiking** [comment]
@felixarntz good catch! Updated.

**Pull request merged**
